version: '3'
services:

  php_laravel:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php_laravel
    privileged: true
    volumes:
      - ./src:/var/www/html
      - phpsocket:/var/run
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-volume:/var/lib/mysql
      - ./db/log/mysql:/var/log/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  ngnix:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: ngnix
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - phpsocket:/var/run
    depends_on:
      - php_laravel

volumes:
  phpsocket:
  db-volume:
